WebImmobilis/Models/ViewModel/Usuario/UsuarioViewModel.cs
using Modelo.TipoUsuario;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WebImmobilis.Models.ViewModel.Propiedad;

namespace WebImmobilis.Models.ViewModel.Usuario
{
    public class UsuarioViewModel
    {
        public Guid UsuarioId { get; set; }
        [Required(ErrorMessage = "El campo Rut es obligatorio")]
        [MaxLength(10, ErrorMessage = "El campo Rut tiene un máximo de 10 carácteres.")]
        public string Rut { get; set; }
        [Required(ErrorMessage = "El campo RutDv es obligatorio")]
        public int RutDv { get; set; }
        [Required(ErrorMessage = "El campo Nombre es obligatorio")]
        [MaxLength(50, ErrorMessage = "El campo Nombre tiene un máximo de 50 carácteres.")]
        [Display(Name = "Nombre")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,50}$", ErrorMessage = "Carácteres no permitidos.")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "El campo Apellido Paterno es obligatorio")]
        [MaxLength(50, ErrorMessage = "El campo Apellido Paterno tiene un máximo de 50 carácteres.")]
        [Display(Name = "Apellido Paterno")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,50}$", ErrorMessage = "Carácteres no permitidos.")]
        public string ApellidoPaterno { get; set; }
        [Required(ErrorMessage = "El campo Apellido Materno es obligatorio")]
        [MaxLength(50, ErrorMessage = "El campo Apellido Materno tiene un máximo de 50 carácteres.")]
        [Display(Name = "Apellido Materno")]
        [RegularExpression(@"^[a-zA-Z''-'\s]{1,50}$", ErrorMessage = "Carácteres no permitidos.")]
        public string ApellidoMaterno { get; set; }
        [Required(ErrorMessage = "El campo Email es obligatorio")]
        [MaxLength(100, ErrorMessage = "El campo Email tiene un máximo de 100 carácteres.")]
        [EmailAddress(ErrorMessage = "Email no válido.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "El campo Clave es obligatorio")]
        [MaxLength(100, ErrorMessage = "El campo Clave tiene un máximo de 100 carácteres.")]
        public string Clave { get; set; }
        [Required(ErrorMessage = "El campo Celular es obligatorio")]
        [MaxLength(10, ErrorMessage = "El campo Celular tiene un máximo de 10 carácteres.")]
        public string Celular { get; set; }
        [Required(ErrorMessage = "El campo Tipo Usuario Id es obligatorio")]
        [Display(Name = "Tipo de Usuario")]
        public int TipoUsuarioId { get; set; }
        public string NombreVista { get; set; }

        public string NombreCompleto {
            get {
                return string.Format("{0} {1} {2}", Nombres, ApellidoPaterno, ApellidoMaterno);
            }
        }
        public List<TipoUsuarioModel> TipoUsuarioList { get; set; }
        public TipoUsuarioModel TipoUsuario { get; set; }
        public List<DepartamentoViewModel> ListaDepartamentosEnReserva { get; set; }
        public List<DepartamentoViewModel> ListaDepartamentosComprados { get; set; }

    }
}

WebImmobilis/Controllers/Usuario/ClienteController.cs
using AutoMapper;
using Modelo.Usuario;
using Negocio.Propiedad;
using Negocio.Usuario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebImmobilis.Controllers.Base;
using WebImmobilis.Mapper;
using WebImmobilis.Models.ViewModel.Propiedad;
using WebImmobilis.Models.ViewModel.Usuario;

[assembly: log4net.Config.XmlConfigurator(Watch = true)]

namespace WebImmobilis.Controllers.Usuario
{
    public class ClienteController : BaseController
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(System.Reflection.MethodBase.GetCurrentMethod().DeclaringType);

        // GET: Cliente
        public ActionResult Index()
        {
            log.Error("This is my error");
            return View();
        }

        public ActionResult MiPerfil()
        {
            var user = GetUser();
            ViewBag.User = GetUser();
            if (user != null)
            {
                var usuarioModel = new UsuarioBusiness().Leer(new Modelo.Usuario.UsuarioModel() { UsuarioId = Guid.Parse(user.UserId) });
                if (usuarioModel.Error == 0)
                {
                    IMapper mapper = AutoMapperConfiguration.RegisterAutoMapper();
                    var usuarioViewModel = mapper.Map<UsuarioViewModel>(usuarioModel);

                    PropiedadBusiness propiedadBusiness = new PropiedadBusiness();

                    //Obtenemos lista de departamentos en reserva
                    var listaDepartamentoEnReserva = propiedadBusiness.ListarPropiedadPorEstado(3, Guid.Parse(user.UserId));
                    usuarioViewModel.ListaDepartamentosEnReserva = new List<DepartamentoViewModel>();
                    //usuarioViewModel.ListaDepartamentosEnReserva = mapper.Map<List<DepartamentoViewModel>>(listaDepartamentoEnReserva);
                    foreach (var item in listaDepartamentoEnReserva)
                    {
                        DepartamentoViewModel departamentoViewModel = new DepartamentoViewModel()
                        {
                            Activo = item.Departamento.Activo,
                            BancoId = item.BancoId,
                            cantidadBanios = item.Departamento.CantidadBanios,
                            cantidadDormitorios = item.Departamento.CantidadDormitorios,
                            ConservadorBienes = item.ConservadorBienes,
                            DepartamentoId = (Guid)item.DepartamentoId,
                            EstadoPropiedadId = item.EstadoPropiedadId,
                            MetrosCuadrados = item.Departamento.MetrosCuadrados,
                            NombreEdificio = item.Departamento.NombreEdificio,
                            PrecioUF = (int)item.PrecioUf,
                            PropiedadId = item.PropiedadId
                        };
                        usuarioViewModel.ListaDepartamentosEnReserva.Add(departamentoViewModel);
                    }

                    //Obtenemos lista de departamentos comprados
                    var listaDepartamentoComprados = propiedadBusiness.ListarPropiedadPorEstado(4, Guid.Parse(user.UserId));
                    usuarioViewModel.ListaDepartamentosComprados = new List<DepartamentoViewModel>();
                    //usuarioViewModel.ListaDepartamentosComprados = mapper.Map<List<DepartamentoViewModel>>(listaDepartamentoComprados);
                    foreach (var item in listaDepartamentoComprados)
                    {
                        DepartamentoViewModel departamentoViewModel = new DepartamentoViewModel()
                        {
                            Activo = item.Departamento.Activo,
                            BancoId = item.BancoId,
                            cantidadBanios = item.Departamento.CantidadBanios,
                            cantidadDormitorios = item.Departamento.CantidadDormitorios,
                            ConservadorBienes = item.ConservadorBienes,
                            DepartamentoId = (Guid)item.DepartamentoId,
                            EstadoPropiedadId = item.EstadoPropiedadId,
                            MetrosCuadrados = item.Departamento.MetrosCuadrados,
                            NombreEdificio = item.Departamento.NombreEdificio,
                            PrecioUF = (int)item.PrecioUf,
                            PropiedadId = item.PropiedadId
                        };
                        usuarioViewModel.ListaDepartamentosComprados.Add(departamentoViewModel);
                    }

                    return View(usuarioViewModel);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, usuarioModel.Mensaje);
                    return View(new UsuarioViewModel());
                }
            }
            return View("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Actualizar(UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                usuarioViewModel.Rut = $"{usuarioViewModel.Rut}-{usuarioViewModel.RutDv}";
                IMapper mapper = AutoMapperConfiguration.RegisterAutoMapper();
                var usuarioModel = mapper.Map<UsuarioModel>(usuarioViewModel);                

                UsuarioBusiness usuarioBusiness = new UsuarioBusiness();
                var usuarioActualizado = usuarioBusiness.Actualizar(usuarioModel);
                if (usuarioActualizado)
                {
                    ModelState.AddModelError(string.Empty, "Datos actualizados correctamente.");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Hubo un problema interno, vuelva a intentar más tarde.");
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Corriga los campos y vuelva intentar.");
            }
            return View("MiPerfil", usuarioViewModel);
        }

    }
}

WebImmobilis/Controllers/Usuario/UsuarioController.cs
using AutoMapper;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Modelo.Usuario;
using Negocio.TipoUsuario;
using Negocio.Usuario;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebImmobilis.Controllers.Base;
using WebImmobilis.DAL.Security;
using WebImmobilis.Helper;
using WebImmobilis.Mapper;
using WebImmobilis.Models.Enum;
using WebImmobilis.Models.ViewModel.Usuario;

namespace WebImmobilis.Controllers.Usuario
{
    public class UsuarioController : BaseController
    {
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult ListarUsuario([DataSourceRequest] DataSourceRequest request)
        {
            UsuarioBusiness usuarioBusiness = new UsuarioBusiness();
            var result = usuarioBusiness.Listar();
            var list = Json(result.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
            return list;
        }

        [HttpGet]
        public ActionResult CrearCliente()
        {
            return View(new UsuarioViewModel() { TipoUsuarioId = (int)EnumTipoUsuario.Cliente, NombreVista = "CrearCliente"});
        }

        [HttpGet]
        public ActionResult Crear()
        {
            UsuarioViewModel usuarioViewModel = new UsuarioViewModel();
            usuarioViewModel.TipoUsuarioList = new TipoUsuarioBusiness().Listar();
            usuarioViewModel.NombreVista = "Crear";
            usuarioViewModel.Clave = "Default";
            return View(usuarioViewModel);
        }

        /// <summary>
        /// Método para crear Usuario para el sistema
        /// </summary>
        /// <param name="usuarioViewModel">Objeto que contiene los datos a ingresar</param>
        /// <returns>Retorna una respuesta si el usuario pudo ser ingresadoc correctamente</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                IMapper mapper = AutoMapperConfiguration.RegisterAutoMapper();
                var usuarioModel = mapper.Map<UsuarioModel>(usuarioViewModel);
                usuarioModel.Rut = string.Format("{0}-{1}", usuarioViewModel.Rut, usuarioViewModel.RutDv);

                string claveUsuario = Guid.NewGuid().ToString().Substring(0, 8);
                if (usuarioModel.TipoUsuarioId == (int)EnumTipoUsuario.Administrador || usuarioModel.TipoUsuarioId == (int)EnumTipoUsuario.Ejecutivo || usuarioModel.TipoUsuarioId == (int)EnumTipoUsuario.Supervisor)
                {
                    usuarioModel.Clave = claveUsuario;
                }

                var usuarioCreado = new UsuarioBusiness().Crear(usuarioModel);
                if (usuarioCreado.Error == 0)
                {
                    ModelState.AddModelError(string.Empty, "Usuario creado correctamente.");
                    //Mensaje de usuario creado con exito
                    if (usuarioCreado.TipoUsuarioId == (int)EnumTipoUsuario.Cliente || usuarioCreado.TipoUsuarioId == (int)EnumTipoUsuario.Propietario)
                    {
                        PutMessage("Usuario Creado correctamente", LevelMessage.Exito);
                        return View("CrearCliente");
                    }
                    else
                    {
                        usuarioViewModel.Clave = claveUsuario;
                        bool correoEnviado = MailHelper.EnviarMailNuevoUsuario(usuarioViewModel);
                        if (correoEnviado)
                        {
                            PutMessage("Usuario Creado correctamente", LevelMessage.Exito);
                        }
                        else
                        {
                            PutMessage("Usuario Creado correctamente, pero no se ha enviado el correo", LevelMessage.Advertencia);
                        }
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, usuarioCreado.Mensaje);
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Por favor, complete los campos y vuelva a intentar.");
            }
            usuarioViewModel.TipoUsuarioList = new TipoUsuarioBusiness().Listar();
            return View(usuarioViewModel.NombreVista,usuarioViewModel);
        }

        public ActionResult Editar(Guid usuarioId)
        {
            var usuarioModel = new UsuarioBusiness().Leer(new UsuarioModel() { UsuarioId = usuarioId });
            IMapper mapper = AutoMapperConfiguration.RegisterAutoMapper();
            var usuarioViewModel= mapper.Map<UsuarioViewModel>(usuarioModel);

            var rutSeparado = usuarioViewModel.Rut.Split('-');
            usuarioViewModel.Rut = rutSeparado[0];
            usuarioViewModel.RutDv = Convert.ToInt32(rutSeparado[1]);
            usuarioViewModel.TipoUsuarioList = new TipoUsuarioBusiness().Listar();
            return View(usuarioViewModel);
        }

        /// <summary>
        /// Método para poder editar los datos de un Usuario
        /// </summary>
        /// <param name="usuarioViewModel"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(UsuarioViewModel usuarioViewModel)
        {
            if (ModelState.IsValid)
            {
                IMapper mapper = AutoMapperConfiguration.RegisterAutoMapper();
                var usuarioModel = mapper.Map<UsuarioModel>(usuarioViewModel);
                usuarioModel.Rut = string.Format("{0}-{1}", usuarioViewModel.Rut, usuarioViewModel.RutDv);

                var usuarioActualizado = new UsuarioBusiness().Actualizar(usuarioModel);
                if (usuarioActualizado)
                {
                    PutMessage("Usuario actualizado correctamente", LevelMessage.Exito);
                    return RedirectToAction("Index");
                }
                ModelState.AddModelError(string.Empty, "Los datos del usuario no se actualizaron, vuelva a intentar más tarde.");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Por favor, complete los campos y vuelva a intentar.");
            }
            usuarioViewModel.TipoUsuarioList = new TipoUsuarioBusiness().Listar();
            return View("Editar", usuarioViewModel);
        }

        public CustomPrincipal ObtenerUsuarioLogueado()
        {
            var usuario = GetUser();
            return usuario;
        }

    }
}

WebImmobilis/Views/Usuario/Crear.cshtml
@model WebImmobilis.Models.ViewModel.Usuario.UsuarioViewModel

@{
    ViewBag.Title = "Crear";
    Layout = "~/Views/Shared/_LayoutIntranet.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <h2>Crear Usuario</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />

                @using (Html.BeginForm("Crear", "Usuario", FormMethod.Post, new { @id = "form1", @class = "form-horizontal form-label-left", enctype = "multipart/form-data", @data_form = "validate" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-dark text-center alert alert-dismissible", @style = "background-color:moccasin;" })

                    @Html.HiddenFor(c => c.NombreVista)
                    @Html.HiddenFor(c => c.Clave)

                    <div class="item form-group">
                        @Html.LabelFor(model => model.Rut, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                        <div class="col-md-6 col-sm-6 ">
                            <div class="row">
                                @Html.EditorFor(model => model.Rut, new { htmlAttributes = new { @class = "form-control form-number form-rut col-sm-10", @placeholder = "Rut", @maxlength = "8", @style = "margin-left:14px;" } })
                                <span style="font-size:28px; font-weight:bold;">-</span>
                                @Html.EditorFor(model => model.RutDv, new { htmlAttributes = new { @class = "form-control form-dv form-dvrut col-sm-1", @placeholder = "Rut", @maxlength = "1", @readonly = "true", @value = "0" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.Rut, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="item form-group">
                        @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                        <div class="col-md-6 col-sm-6 ">
                            @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control", @maxlength = "50" } })
                            @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class=" item form-group">
                        @Html.LabelFor(model => model.ApellidoPaterno, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                        <div class="col-md-6 col-sm-6 ">
                            @Html.EditorFor(model => model.ApellidoPaterno, new { htmlAttributes = new { @class = "form-control", @maxlength = "50" } })
                            @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class=" item form-group">
                        @Html.LabelFor(model => model.ApellidoMaterno, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                        <div class="col-md-6 col-sm-6 ">
                            @Html.EditorFor(model => model.ApellidoMaterno, new { htmlAttributes = new { @class = "form-control", @maxlength = "50" } })
                            @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="item form-group row">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                        <div class="col-md-6 col-sm-6 ">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @maxlength = "100" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*<div class="item form-group">
                @Html.LabelFor(model => model.Clave, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                <div class="col-md-6 col-sm-6 ">
                    @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control", @type = "password", @maxlength = "100"  } })
                    @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
                </div>
            </div>*@

                    <div class="item form-group">
                        @Html.LabelFor(model => model.Celular, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                        <div class="col-md-6 col-sm-6 ">
                            @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control form-number", @maxlength = "9" } })
                            @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="item form-group">
                        @Html.LabelFor(model => model.TipoUsuarioId, htmlAttributes: new { @class = "col-form-label col-md-3 col-sm-3 label-align" })
                        <div class="col-md-6 col-sm-6 ">
                            @Html.DropDownListFor(model => model.TipoUsuarioId, new SelectList(Model.TipoUsuarioList, "TipoUsuarioId", "Nombre"), "Seleccione Tipo de Usuario", new { @class = "form-control", @value = "0" })
                            @Html.ValidationMessageFor(model => model.TipoUsuarioId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="ln_solid"></div>
                    <div class="item form-group">
                        <div class="col-md-6 col-sm-6 offset-md-6">
                            <a class="btn btn-secondary" href="/Usuario/Index">Cancelar</a>
                            <button type="submit" class="btn btn-success">Guardar</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

WebImmobilis/Views/Usuario/CrearCliente.cshtml
@model WebImmobilis.Models.ViewModel.Usuario.UsuarioViewModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Ecoverde - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/Home/css/animate.css">
    <link rel="stylesheet" href="~/Content/Home/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/Home/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/Content/Home/css/magnific-popup.css">
    <link rel="stylesheet" href="~/Content/Home/css/flaticon.css">
    <link rel="stylesheet" href="~/Content/Home/css/style.css">
</head>
<body>

    @Html.Partial("/Views/Home/Partial/_Navegador.cshtml")

    <section class="hero-wrap hero-wrap-2" style="background-image: url('images/bg_1.jpg'); height:100px!important;" data-stellar-background-ratio="0.5">
        <div class="overlay" style="height:100px !important;"></div>
    </section>

    <section class="ftco-section contact-section" style="padding: 3em 0;">
        <div class="container">
            <div class="row block-9 justify-content-center mb-5">
                <div class="col-md-8 mb-md-5">
                    <h2 class="text-center">Completa los siguientes campos para registrarte</h2>

                    @using (Html.BeginForm("Crear", "Usuario", FormMethod.Post, new { @id = "form1", @class = "bg-light p-1 contact-form", enctype = "multipart/form-data", @data_form = "validate" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.ValidationSummary(true, "", new { @class = "alert alert-warning" })
                        @Html.HiddenFor(c => c.TipoUsuarioId)
                        @Html.HiddenFor(c => c.NombreVista)

                        <div class="form-group">
                            <div class="row">
                                @Html.EditorFor(model => model.Rut, new { htmlAttributes = new { @class = "form-control form-number form-rut col-sm-10", @placeholder = "Rut", @maxlength = "8", @style = "margin-left:14px;" } })
                                <span style="font-size:28px; font-weight:bold;">-</span>
                                @Html.EditorFor(model => model.RutDv, new { htmlAttributes = new { @class = "form-control form-dv form-dvrut col-sm-1", @placeholder = "Rut", @maxlength = "1", @readonly = "true", @value = "0" } })
                            </div>
                            @Html.ValidationMessageFor(model => model.Rut, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control", @placeholder = "Nombre", @maxlength = "50" } })
                            @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.EditorFor(model => model.ApellidoPaterno, new { htmlAttributes = new { @class = "form-control", @placeholder = "Apellido Paterno", @maxlength = "50" } })
                            @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.EditorFor(model => model.ApellidoMaterno, new { htmlAttributes = new { @class = "form-control", @placeholder = "Apellido Materno", @maxlength = "50" } })
                            @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email", @maxlength = "100" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control", @type = "password", @placeholder = "Contraseña", @maxlength = "100" } })
                            @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            @Html.EditorFor(model => model.Celular, new { htmlAttributes = new { @class = "form-control form-number", @placeholder = "Celular", @maxlength = "9" } })
                            @Html.ValidationMessageFor(model => model.Celular, "", new { @class = "text-danger" })
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Registrarme" class="btn btn-success py-3 px-5" />
                        </div>
                    }

                </div>
            </div>

        </div>
    </section>

    <footer class="ftco-footer ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">

                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>
            </div>
        </div>
    </footer>



    <!-- loader -->
    <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" /><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00" /></svg></div>


    <script src="~/Content/Home/js/jquery.min.js"></script>
    <script src="~/Content/Home/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/Content/Home/js/popper.min.js"></script>
    <script src="~/Content/Home/js/bootstrap.min.js"></script>
    <script src="~/Content/Home/js/jquery.easing.1.3.js"></script>
    <script src="~/Content/Home/js/jquery.waypoints.min.js"></script>
    <script src="~/Content/Home/js/jquery.stellar.min.js"></script>
    <script src="~/Content/Home/js/owl.carousel.min.js"></script>
    <script src="~/Content/Home/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/Home/js/jquery.animateNumber.min.js"></script>
    <script src="~/Content/Home/js/scrollax.min.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
    <script src="~/Content/Home/js/google-map.js"></script>
    <script src="~/Content/Home/js/main.js"></script>
    @Scripts.Render("~/bundles/codebase")

</body>
</html>